In [2]:
import numpy as np

# Define matrix a (3x3)
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Define vector b (3x1)
b = np.array([2, 1, 3])

# Perform matrix-vector multiplication
result = a @ b

# Display the result
print("Resultant Matrix:")
print(result)


Resultant Matrix:
[13 31 49]


In [4]:
import numpy as np

# Get user input for matrix dimensions
rows_a = int(input("Enter the number of rows for matrix a: "))
cols_a = int(input("Enter the number of columns for matrix a: "))

# Get user input for matrix a
print("Enter elements for matrix a:")
a = np.array([[float(input()) for j in range(cols_a)] for i in range(rows_a)])

# Get user input for vector dimensions
rows_b = int(input("Enter the number of rows for vector b: "))

# Get user input for vector b
print("Enter elements for vector b:")
b = np.array([float(input()) for i in range(rows_b)])

# Perform matrix-vector multiplication
result = a @ b

# Display the result
print("Resultant Matrix:")
print(result)


Enter the number of rows for matrix a: 3
Enter the number of columns for matrix a: 3
Enter elements for matrix a:
1
2
3
4
5
6
7
8
9
Enter the number of rows for vector b: 3
Enter elements for vector b:
1
2
3
Resultant Matrix:
[14. 32. 50.]


In [6]:
import numpy as np

# Define matrices and vectors
m1 = np.array([[1, 2], [3, 4]])  # Replace with your matrix
m = np.array([[5, 6], [7, 8]])    # Replace with your matrix

# Matrix multiplication using np.matmul
result_multiply = np.matmul(m1, m)
print("Matrix Multiplication Result:")
print(result_multiply)

# Transposition using np.transpose
result_transpose = np.transpose(m)
print("\nTransposed Matrix:")
print(result_transpose)

# Matrix inversion using np.linalg.inv
result_inverse = np.linalg.inv(m)
print("\nInverse Matrix:")
print(result_inverse)


Matrix Multiplication Result:
[[19 22]
 [43 50]]

Transposed Matrix:
[[5 7]
 [6 8]]

Inverse Matrix:
[[-4.   3. ]
 [ 3.5 -2.5]]
